services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/.venv  # Exclude virtual environment from volume mount
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  test-runner:
    build: .
    volumes:
      - ./output:/app/output
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    command: tail -f /dev/null  # Keep container running for manual testing
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: lovable_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lovable_db
      MYSQL_USER: lovable_user
      MYSQL_PASSWORD: lovable_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
