version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PYTHONPATH=/app/src
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network
    command: sh -c "cd /app && python3 src/server.py & sleep 3 && npm run serve"

  test-runner:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network
    command: sleep infinity

  mysql:
    image: mysql:8.0
    container_name: lovable_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lovable_db
      MYSQL_USER: lovable_user
      MYSQL_PASSWORD: lovable_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
