services:
  web:
    build: .
    ports:
      - "5001:5001"  # Flask backend
      - "8080:8080"  # Vue.js frontend dev server
      - "3000:3000"  # Generated Vue.js sites dev server
    volumes:
      - .:/app
      - /app/.venv  # Exclude virtual environment from volume mount
      - /app/node_modules  # Exclude node_modules from volume mount
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - NODE_ENV=development
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  test-runner:
    build: .
    volumes:
      - ./output:/app/output
      - ./tests:/app/tests
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=testing
    networks:
      - app-network
    ports:
      - "5002:5002"  # Separate port for testing generated sites
    command: sh -c "cd /app/output && python3 -m http.server 5002 2>/dev/null || tail -f /dev/null"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: lovable_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lovable_db
      MYSQL_USER: lovable_user
      MYSQL_PASSWORD: lovable_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
